export interface IMeeting {
  start_date: number,
  end_date: number,
  startup: string,
  purpose: string,
  attendees: any[],
  partner: string,
  meetingUrl: string,
  id: number,
  notes: any[],
  meeting_id: number,
  ratingFromStartup?: number,
  punctualityFromStartup?: number,
  notesFromStartup?: string,
  ratingFromPartner?: number,
  punctualityFromPartner?: number,
  notesFromPartner?: string,
}

export interface IStartup {
  id: number,
  name: string,
  logo_url: string,
  industry: string,
  description: string,
  web_site_url: string,
  hq_country: string,
  founding_date: string,
  founding_stage: string,
  start_up_status: string,
  total_founding: string,
  current_employee_count: number,
  business_model: string,
  old_accelerator_programs: string,
  fs_incubation_participant: boolean,
  fs_accelerator_participant: string,
  equity_free_investments_by_fs: string,
  pitch_deck_url: string,
}